version: '3.7'

services:
  backend:
    container_name: zazu_backend
    restart: always
    build:
      network: host
      context: .
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
    volumes:
      - ./src:/var/www/backend/src
    working_dir: /var/www/backend
    ports:
      - '3000:3000'
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    container_name: zazu_mysql
    restart: always
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - '3307:3306'

networks:
  default:
    external:
      name: app
